# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/book_reg_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_book_reg_window(object):
    def setupUi(self, book_reg_window):
        book_reg_window.setObjectName("book_reg_window")
        book_reg_window.resize(609, 429)
        self.centralwidget = QtWidgets.QWidget(book_reg_window)
        self.centralwidget.setObjectName("centralwidget")
        self.category_input = QtWidgets.QTextEdit(self.centralwidget)
        self.category_input.setGeometry(QtCore.QRect(200, 50, 241, 31))
        self.category_input.setObjectName("category_input")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(60, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.Year = QtWidgets.QLabel(self.centralwidget)
        self.Year.setGeometry(QtCore.QRect(60, 170, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Year.setFont(font)
        self.Year.setObjectName("Year")
        self.Press = QtWidgets.QLabel(self.centralwidget)
        self.Press.setGeometry(QtCore.QRect(60, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Press.setFont(font)
        self.Press.setObjectName("Press")
        self.Author = QtWidgets.QLabel(self.centralwidget)
        self.Author.setGeometry(QtCore.QRect(60, 210, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Author.setFont(font)
        self.Author.setObjectName("Author")
        self.year_input = QtWidgets.QTextEdit(self.centralwidget)
        self.year_input.setGeometry(QtCore.QRect(200, 170, 91, 31))
        self.year_input.setObjectName("year_input")
        self.Category = QtWidgets.QLabel(self.centralwidget)
        self.Category.setGeometry(QtCore.QRect(60, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Category.setFont(font)
        self.Category.setObjectName("Category")
        self.press_input = QtWidgets.QTextEdit(self.centralwidget)
        self.press_input.setGeometry(QtCore.QRect(200, 130, 241, 31))
        self.press_input.setObjectName("press_input")
        self.author_input = QtWidgets.QTextEdit(self.centralwidget)
        self.author_input.setGeometry(QtCore.QRect(200, 210, 241, 31))
        self.author_input.setObjectName("author_input")
        self.Price = QtWidgets.QLabel(self.centralwidget)
        self.Price.setGeometry(QtCore.QRect(60, 250, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Price.setFont(font)
        self.Price.setObjectName("Price")
        self.title_input = QtWidgets.QTextEdit(self.centralwidget)
        self.title_input.setGeometry(QtCore.QRect(200, 90, 241, 31))
        self.title_input.setObjectName("title_input")
        self.price_input = QtWidgets.QTextEdit(self.centralwidget)
        self.price_input.setGeometry(QtCore.QRect(200, 250, 91, 31))
        self.price_input.setObjectName("price_input")
        self.ReturnButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.ReturnButton.setGeometry(QtCore.QRect(490, 0, 101, 48))
        self.ReturnButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ReturnButton.setObjectName("ReturnButton")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(200, 290, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName("SearchButton")
        book_reg_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(book_reg_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 26))
        self.menubar.setObjectName("menubar")
        book_reg_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(book_reg_window)
        self.statusbar.setObjectName("statusbar")
        book_reg_window.setStatusBar(self.statusbar)

        self.retranslateUi(book_reg_window)
        QtCore.QMetaObject.connectSlotsByName(book_reg_window)

    def retranslateUi(self, book_reg_window):
        _translate = QtCore.QCoreApplication.translate
        book_reg_window.setWindowTitle(_translate("book_reg_window", "book_reg_window"))
        self.Title.setText(_translate("book_reg_window", "Title:"))
        self.Year.setText(_translate("book_reg_window", "Year:"))
        self.Press.setText(_translate("book_reg_window", "Press:"))
        self.Author.setText(_translate("book_reg_window", "Author:"))
        self.Category.setText(_translate("book_reg_window", "Category:"))
        self.Price.setText(_translate("book_reg_window", "Price:"))
        self.ReturnButton.setText(_translate("book_reg_window", "Return"))
        self.SearchButton.setText(_translate("book_reg_window", "Registration"))
