# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/BR_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BR_window(object):
    def setupUi(self, BR_window):
        BR_window.setObjectName("BR_window")
        BR_window.resize(595, 390)
        self.centralwidget = QtWidgets.QWidget(BR_window)
        self.centralwidget.setObjectName("centralwidget")
        self.BorrowButton = QtWidgets.QPushButton(self.centralwidget)
        self.BorrowButton.setGeometry(QtCore.QRect(120, 270, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.BorrowButton.setFont(font)
        self.BorrowButton.setCheckable(False)
        self.BorrowButton.setChecked(False)
        self.BorrowButton.setAutoDefault(False)
        self.BorrowButton.setDefault(False)
        self.BorrowButton.setFlat(False)
        self.BorrowButton.setObjectName("BorrowButton")
        self.ReturnButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReturnButton.setGeometry(QtCore.QRect(330, 270, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.ReturnButton.setFont(font)
        self.ReturnButton.setObjectName("ReturnButton")
        self.Book_no = QtWidgets.QLabel(self.centralwidget)
        self.Book_no.setGeometry(QtCore.QRect(70, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Book_no.setFont(font)
        self.Book_no.setObjectName("Book_no")
        self.bno_input = QtWidgets.QTextEdit(self.centralwidget)
        self.bno_input.setGeometry(QtCore.QRect(230, 200, 241, 31))
        self.bno_input.setObjectName("bno_input")
        self.cno_input = QtWidgets.QTextEdit(self.centralwidget)
        self.cno_input.setGeometry(QtCore.QRect(230, 10, 241, 31))
        self.cno_input.setObjectName("cno_input")
        self.Card_no = QtWidgets.QLabel(self.centralwidget)
        self.Card_no.setGeometry(QtCore.QRect(70, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Card_no.setFont(font)
        self.Card_no.setObjectName("Card_no")
        self.Book_borrowed = QtWidgets.QLabel(self.centralwidget)
        self.Book_borrowed.setGeometry(QtCore.QRect(70, 60, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Book_borrowed.setFont(font)
        self.Book_borrowed.setObjectName("Book_borrowed")
        self.borrowed_output = QtWidgets.QLabel(self.centralwidget)
        self.borrowed_output.setGeometry(QtCore.QRect(230, 60, 241, 121))
        self.borrowed_output.setMouseTracking(False)
        self.borrowed_output.setTabletTracking(False)
        self.borrowed_output.setAcceptDrops(False)
        self.borrowed_output.setAutoFillBackground(False)
        self.borrowed_output.setText("")
        self.borrowed_output.setScaledContents(False)
        self.borrowed_output.setWordWrap(False)
        self.borrowed_output.setOpenExternalLinks(False)
        self.borrowed_output.setObjectName("borrowed_output")
        self.ReturnButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.ReturnButton_2.setGeometry(QtCore.QRect(490, 0, 101, 48))
        self.ReturnButton_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ReturnButton_2.setObjectName("ReturnButton_2")
        BR_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BR_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 26))
        self.menubar.setObjectName("menubar")
        BR_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BR_window)
        self.statusbar.setObjectName("statusbar")
        BR_window.setStatusBar(self.statusbar)

        self.retranslateUi(BR_window)
        QtCore.QMetaObject.connectSlotsByName(BR_window)

    def retranslateUi(self, BR_window):
        _translate = QtCore.QCoreApplication.translate
        BR_window.setWindowTitle(_translate("BR_window", "BR_window"))
        self.BorrowButton.setText(_translate("BR_window", "Borrow"))
        self.ReturnButton.setText(_translate("BR_window", "Return"))
        self.Book_no.setText(_translate("BR_window", "Book_no:"))
        self.Card_no.setText(_translate("BR_window", "Card_no:"))
        self.Book_borrowed.setText(_translate("BR_window", "Borrowed books:"))
        self.ReturnButton_2.setText(_translate("BR_window", "Return"))
