# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/search_book_widget.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_book_widget(object):
    def setupUi(self, search_book_widget):
        search_book_widget.setObjectName("search_book_widget")
        search_book_widget.resize(573, 419)
        self.author_input = QtWidgets.QTextEdit(search_book_widget)
        self.author_input.setGeometry(QtCore.QRect(200, 240, 241, 31))
        self.author_input.setObjectName("author_input")
        self.Press = QtWidgets.QLabel(search_book_widget)
        self.Press.setGeometry(QtCore.QRect(60, 160, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Press.setFont(font)
        self.Press.setObjectName("Press")
        self.Category = QtWidgets.QLabel(search_book_widget)
        self.Category.setGeometry(QtCore.QRect(60, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Category.setFont(font)
        self.Category.setObjectName("Category")
        self.press_input = QtWidgets.QTextEdit(search_book_widget)
        self.press_input.setGeometry(QtCore.QRect(200, 160, 241, 31))
        self.press_input.setObjectName("press_input")
        self.Author = QtWidgets.QLabel(search_book_widget)
        self.Author.setGeometry(QtCore.QRect(60, 240, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Author.setFont(font)
        self.Author.setObjectName("Author")
        self.SearchButton = QtWidgets.QPushButton(search_book_widget)
        self.SearchButton.setGeometry(QtCore.QRect(200, 330, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName("SearchButton")
        self.category_input = QtWidgets.QTextEdit(search_book_widget)
        self.category_input.setGeometry(QtCore.QRect(200, 80, 241, 31))
        self.category_input.setObjectName("category_input")
        self.ReturnButton = QtWidgets.QCommandLinkButton(search_book_widget)
        self.ReturnButton.setGeometry(QtCore.QRect(470, 10, 101, 48))
        self.ReturnButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ReturnButton.setObjectName("ReturnButton")
        self.Year = QtWidgets.QLabel(search_book_widget)
        self.Year.setGeometry(QtCore.QRect(60, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Year.setFont(font)
        self.Year.setObjectName("Year")
        self.price_input_to = QtWidgets.QTextEdit(search_book_widget)
        self.price_input_to.setGeometry(QtCore.QRect(350, 280, 91, 31))
        self.price_input_to.setObjectName("price_input_to")
        self.Year_from = QtWidgets.QLabel(search_book_widget)
        self.Year_from.setGeometry(QtCore.QRect(150, 200, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Year_from.setFont(font)
        self.Year_from.setObjectName("Year_from")
        self.Price = QtWidgets.QLabel(search_book_widget)
        self.Price.setGeometry(QtCore.QRect(60, 280, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Price.setFont(font)
        self.Price.setObjectName("Price")
        self.Title = QtWidgets.QLabel(search_book_widget)
        self.Title.setGeometry(QtCore.QRect(60, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.year_input_from = QtWidgets.QTextEdit(search_book_widget)
        self.year_input_from.setGeometry(QtCore.QRect(200, 200, 91, 31))
        self.year_input_from.setObjectName("year_input_from")
        self.Price_to = QtWidgets.QLabel(search_book_widget)
        self.Price_to.setGeometry(QtCore.QRect(310, 280, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Price_to.setFont(font)
        self.Price_to.setObjectName("Price_to")
        self.Year_to = QtWidgets.QLabel(search_book_widget)
        self.Year_to.setGeometry(QtCore.QRect(310, 200, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Year_to.setFont(font)
        self.Year_to.setObjectName("Year_to")
        self.Price_from = QtWidgets.QLabel(search_book_widget)
        self.Price_from.setGeometry(QtCore.QRect(150, 280, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Price_from.setFont(font)
        self.Price_from.setObjectName("Price_from")
        self.title_input = QtWidgets.QTextEdit(search_book_widget)
        self.title_input.setGeometry(QtCore.QRect(200, 120, 241, 31))
        self.title_input.setObjectName("title_input")
        self.year_input_to = QtWidgets.QTextEdit(search_book_widget)
        self.year_input_to.setGeometry(QtCore.QRect(350, 200, 91, 31))
        self.year_input_to.setObjectName("year_input_to")
        self.price_input_from = QtWidgets.QTextEdit(search_book_widget)
        self.price_input_from.setGeometry(QtCore.QRect(200, 280, 91, 31))
        self.price_input_from.setObjectName("price_input_from")

        self.retranslateUi(search_book_widget)
        QtCore.QMetaObject.connectSlotsByName(search_book_widget)

    def retranslateUi(self, search_book_widget):
        _translate = QtCore.QCoreApplication.translate
        search_book_widget.setWindowTitle(_translate("search_book_widget", "search_book_widget"))
        self.Press.setText(_translate("search_book_widget", "Press:"))
        self.Category.setText(_translate("search_book_widget", "Category:"))
        self.Author.setText(_translate("search_book_widget", "Author:"))
        self.SearchButton.setText(_translate("search_book_widget", "Search"))
        self.ReturnButton.setText(_translate("search_book_widget", "Return"))
        self.Year.setText(_translate("search_book_widget", "Year:"))
        self.Year_from.setText(_translate("search_book_widget", "from"))
        self.Price.setText(_translate("search_book_widget", "Price:"))
        self.Title.setText(_translate("search_book_widget", "Title:"))
        self.Price_to.setText(_translate("search_book_widget", "to"))
        self.Year_to.setText(_translate("search_book_widget", "to"))
        self.Price_from.setText(_translate("search_book_widget", "from"))
