# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/search_book_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_book_window(object):
    def setupUi(self, search_book_window):
        search_book_window.setObjectName("search_book_window")
        search_book_window.resize(670, 464)
        search_book_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(search_book_window)
        self.centralwidget.setObjectName("centralwidget")
        self.ReturnButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.ReturnButton.setGeometry(QtCore.QRect(550, 0, 101, 48))
        self.ReturnButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ReturnButton.setObjectName("ReturnButton")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(250, 330, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName("SearchButton")
        self.Category = QtWidgets.QLabel(self.centralwidget)
        self.Category.setGeometry(QtCore.QRect(110, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Category.setFont(font)
        self.Category.setObjectName("Category")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(110, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.Press = QtWidgets.QLabel(self.centralwidget)
        self.Press.setGeometry(QtCore.QRect(110, 160, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Press.setFont(font)
        self.Press.setObjectName("Press")
        self.Year = QtWidgets.QLabel(self.centralwidget)
        self.Year.setGeometry(QtCore.QRect(110, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Year.setFont(font)
        self.Year.setObjectName("Year")
        self.Author = QtWidgets.QLabel(self.centralwidget)
        self.Author.setGeometry(QtCore.QRect(110, 240, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Author.setFont(font)
        self.Author.setObjectName("Author")
        self.Price = QtWidgets.QLabel(self.centralwidget)
        self.Price.setGeometry(QtCore.QRect(110, 280, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Price.setFont(font)
        self.Price.setObjectName("Price")
        self.category_input = QtWidgets.QTextEdit(self.centralwidget)
        self.category_input.setGeometry(QtCore.QRect(250, 80, 241, 31))
        self.category_input.setObjectName("category_input")
        self.title_input = QtWidgets.QTextEdit(self.centralwidget)
        self.title_input.setGeometry(QtCore.QRect(250, 120, 241, 31))
        self.title_input.setObjectName("title_input")
        self.press_input = QtWidgets.QTextEdit(self.centralwidget)
        self.press_input.setGeometry(QtCore.QRect(250, 160, 241, 31))
        self.press_input.setObjectName("press_input")
        self.author_input = QtWidgets.QTextEdit(self.centralwidget)
        self.author_input.setGeometry(QtCore.QRect(250, 240, 241, 31))
        self.author_input.setObjectName("author_input")
        self.price_input_from = QtWidgets.QTextEdit(self.centralwidget)
        self.price_input_from.setGeometry(QtCore.QRect(250, 280, 91, 31))
        self.price_input_from.setObjectName("price_input_from")
        self.price_input_to = QtWidgets.QTextEdit(self.centralwidget)
        self.price_input_to.setGeometry(QtCore.QRect(400, 280, 91, 31))
        self.price_input_to.setObjectName("price_input_to")
        self.Price_from = QtWidgets.QLabel(self.centralwidget)
        self.Price_from.setGeometry(QtCore.QRect(200, 280, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Price_from.setFont(font)
        self.Price_from.setObjectName("Price_from")
        self.Price_to = QtWidgets.QLabel(self.centralwidget)
        self.Price_to.setGeometry(QtCore.QRect(360, 280, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Price_to.setFont(font)
        self.Price_to.setObjectName("Price_to")
        self.year_input_from = QtWidgets.QTextEdit(self.centralwidget)
        self.year_input_from.setGeometry(QtCore.QRect(250, 200, 91, 31))
        self.year_input_from.setObjectName("year_input_from")
        self.year_input_to = QtWidgets.QTextEdit(self.centralwidget)
        self.year_input_to.setGeometry(QtCore.QRect(400, 200, 91, 31))
        self.year_input_to.setObjectName("year_input_to")
        self.Year_from = QtWidgets.QLabel(self.centralwidget)
        self.Year_from.setGeometry(QtCore.QRect(200, 200, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Year_from.setFont(font)
        self.Year_from.setObjectName("Year_from")
        self.Year_to = QtWidgets.QLabel(self.centralwidget)
        self.Year_to.setGeometry(QtCore.QRect(360, 200, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Year_to.setFont(font)
        self.Year_to.setObjectName("Year_to")
        search_book_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(search_book_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 26))
        self.menubar.setObjectName("menubar")
        search_book_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(search_book_window)
        self.statusbar.setObjectName("statusbar")
        search_book_window.setStatusBar(self.statusbar)

        self.retranslateUi(search_book_window)
        QtCore.QMetaObject.connectSlotsByName(search_book_window)

    def retranslateUi(self, search_book_window):
        _translate = QtCore.QCoreApplication.translate
        search_book_window.setWindowTitle(_translate("search_book_window", "search_book_window"))
        self.ReturnButton.setText(_translate("search_book_window", "Return"))
        self.SearchButton.setText(_translate("search_book_window", "Search"))
        self.Category.setText(_translate("search_book_window", "Category:"))
        self.Title.setText(_translate("search_book_window", "Title:"))
        self.Press.setText(_translate("search_book_window", "Press:"))
        self.Year.setText(_translate("search_book_window", "Year:"))
        self.Author.setText(_translate("search_book_window", "Author:"))
        self.Price.setText(_translate("search_book_window", "Price:"))
        self.Price_from.setText(_translate("search_book_window", "from"))
        self.Price_to.setText(_translate("search_book_window", "to"))
        self.Year_from.setText(_translate("search_book_window", "from"))
        self.Year_to.setText(_translate("search_book_window", "to"))
